package com.ecommerce.output.entities;

// default package
// Generated Mar 15, 2016 3:11:22 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CarddetailsId generated by hbm2java
 */
@Embeddable
public class CarddetailsId implements java.io.Serializable {

	private int customerId;
	private String cardNumber;
	private String pin;
	private Date cardExpiryDtm;
	private String cardType;
	private String bankName;

	public CarddetailsId() {
	}

	public CarddetailsId(int customerId, String cardNumber, String pin, Date cardExpiryDtm, String cardType) {
		this.customerId = customerId;
		this.cardNumber = cardNumber;
		this.pin = pin;
		this.cardExpiryDtm = cardExpiryDtm;
		this.cardType = cardType;
	}

	public CarddetailsId(int customerId, String cardNumber, String pin, Date cardExpiryDtm, String cardType,
			String bankName) {
		this.customerId = customerId;
		this.cardNumber = cardNumber;
		this.pin = pin;
		this.cardExpiryDtm = cardExpiryDtm;
		this.cardType = cardType;
		this.bankName = bankName;
	}

	@Column(name = "CUSTOMER_ID", nullable = false)
	public int getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}

	@Column(name = "CARD_NUMBER", nullable = false, length = 20)
	public String getCardNumber() {
		return this.cardNumber;
	}

	public void setCardNumber(String cardNumber) {
		this.cardNumber = cardNumber;
	}

	@Column(name = "PIN", nullable = false, length = 4)
	public String getPin() {
		return this.pin;
	}

	public void setPin(String pin) {
		this.pin = pin;
	}

	@Column(name = "CARD_EXPIRY_DTM", nullable = false, length = 19)
	public Date getCardExpiryDtm() {
		return this.cardExpiryDtm;
	}

	public void setCardExpiryDtm(Date cardExpiryDtm) {
		this.cardExpiryDtm = cardExpiryDtm;
	}

	@Column(name = "CARD_TYPE", nullable = false, length = 20)
	public String getCardType() {
		return this.cardType;
	}

	public void setCardType(String cardType) {
		this.cardType = cardType;
	}

	@Column(name = "BANK_NAME", length = 20)
	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CarddetailsId))
			return false;
		CarddetailsId castOther = (CarddetailsId) other;

		return (this.getCustomerId() == castOther.getCustomerId())
				&& ((this.getCardNumber() == castOther.getCardNumber()) || (this.getCardNumber() != null
						&& castOther.getCardNumber() != null && this.getCardNumber().equals(castOther.getCardNumber())))
				&& ((this.getPin() == castOther.getPin()) || (this.getPin() != null && castOther.getPin() != null
						&& this.getPin().equals(castOther.getPin())))
				&& ((this.getCardExpiryDtm() == castOther.getCardExpiryDtm())
						|| (this.getCardExpiryDtm() != null && castOther.getCardExpiryDtm() != null
								&& this.getCardExpiryDtm().equals(castOther.getCardExpiryDtm())))
				&& ((this.getCardType() == castOther.getCardType()) || (this.getCardType() != null
						&& castOther.getCardType() != null && this.getCardType().equals(castOther.getCardType())))
				&& ((this.getBankName() == castOther.getBankName()) || (this.getBankName() != null
						&& castOther.getBankName() != null && this.getBankName().equals(castOther.getBankName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCustomerId();
		result = 37 * result + (getCardNumber() == null ? 0 : this.getCardNumber().hashCode());
		result = 37 * result + (getPin() == null ? 0 : this.getPin().hashCode());
		result = 37 * result + (getCardExpiryDtm() == null ? 0 : this.getCardExpiryDtm().hashCode());
		result = 37 * result + (getCardType() == null ? 0 : this.getCardType().hashCode());
		result = 37 * result + (getBankName() == null ? 0 : this.getBankName().hashCode());
		return result;
	}

}
