package com.ecommerce.output.entities;

// default package
// Generated Mar 15, 2016 3:11:22 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Carddetails generated by hbm2java
 */
@Entity
@Table(name = "CARDDETAILS", catalog = "Ankita")
public class Carddetails implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private CarddetailsId id;

	public Carddetails() {
	}

	public Carddetails(CarddetailsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "customerId", column = @Column(name = "CUSTOMER_ID", nullable = false) ),
			@AttributeOverride(name = "cardNumber", column = @Column(name = "CARD_NUMBER", nullable = false, length = 20) ),
			@AttributeOverride(name = "pin", column = @Column(name = "PIN", nullable = false, length = 4) ),
			@AttributeOverride(name = "cardExpiryDtm", column = @Column(name = "CARD_EXPIRY_DTM", nullable = false, length = 19) ),
			@AttributeOverride(name = "cardType", column = @Column(name = "CARD_TYPE", nullable = false, length = 20) ),
			@AttributeOverride(name = "bankName", column = @Column(name = "BANK_NAME", length = 20) ) })
	public CarddetailsId getId() {
		return this.id;
	}

	public void setId(CarddetailsId id) {
		this.id = id;
	}

}
