package com.ecommerce.output.entities;

// default package
// Generated Mar 15, 2016 3:11:22 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cartdetails generated by hbm2java
 */
@Entity
@Table(name = "CARTDETAILS", catalog = "Ankita")
public class Cartdetails implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer cartId;
	private int customerId;
	private String productList;

	public Cartdetails() {
	}

	public Cartdetails(int customerId) {
		this.customerId = customerId;
	}

	public Cartdetails(int customerId, String productList) {
		this.customerId = customerId;
		this.productList = productList;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CART_ID", unique = true, nullable = false)
	public Integer getCartId() {
		return this.cartId;
	}

	public void setCartId(Integer cartId) {
		this.cartId = cartId;
	}

	@Column(name = "CUSTOMER_ID", nullable = false)
	public int getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}

	@Column(name = "PRODUCT_LIST", length = 55)
	public String getProductList() {
		return this.productList;
	}

	public void setProductList(String productList) {
		this.productList = productList;
	}

}
